In [4]:
import numpy as np
import gridlink as g
grid = g.Gridlink(None, (4,8))

In [7]:
values = np.array(len(grid.sensory_cells)*[1])
grid.write_active_cells(values)

In [8]:
grid.read_all()

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [1]:
import numpy as np
import numpy.testing as npt
import gridlink as g

class ModelPatch():
    def __init__(self):
        self.observations = []

    def observe(self, observation):
        self.observations.append(observation)
    
agent = ModelPatch()
test_grid = g.Gridlink(agent, (1,4),(1,2))
N_PREDICTABLE_CYCLES = 2

ones = np.ones(len(test_grid.sensory_cells))
zeros = np.zeros(len(test_grid.sensory_cells))

exp_obs = [ones,zeros,ones,zeros]
test_grid._predictable_feedback()

In [2]:
agent.observations

[array([[0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.]])]

In [16]:
np.random.randint(0,2,(5,2))

array([[1, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 0]])

In [23]:
a = [np.zeros(2), np.zeros(2)]
b = np.zeros((2,2))

In [24]:
np.testing.assert_array_equal(a,b)

In [25]:
rng = np.random.default_rng(seed=42)

In [32]:
rng.integers(0, 2, (2,2))

array([[1, 1],
       [0, 1]])

In [33]:
rng.integers(0,2,20)

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [2]:
class A: 
    def f(self):
        raise NotImplementedError("test")

a = A()
a.f()

NotImplementedError: test

## Sensory feedback

In [10]:
paddle_y = 100
ball_y = -100
rows = 4

round((paddle_y / ball_y) % rows)

3